#+TITLE: JavaScript
#+DESCRIPTION: JavaScript Notes
#+AUTHOR: Linux-DEX

* JavaScript
+ *JavaScript* is a lightweight, interpreted *programming* language. It is commonly used to create dynamic and interactive elements in web applications.
+ *Javascript* is /open and cross-platform/.
+ Javascript is an ~asynchronous~ and concurrent programming language that offers a lot of flexibility. It's single-threaded like synchronous but also non-blocking like asynchronous.

** Client-side JavaScript
+ *The browser processes the code instead of the web server*.
+ Client-side script are commonly uesd when we want to validate data before sending it to the web server, adjusting the interface in response to user feedback, and for implementing other advanced features.

** Server-side JavaScript
+ Server-side javascript is *the use of the javascript language on servers*.
+ *Node.js* is one of the best and most popular Javascript runtime environments for building the server of applications using javascript.
+ Using *Node.js*, we can execute the javascript code outside the browser and manage the server task.

** Limitations of Javascript
+ Client-side JS does not allow the reading or writing of files. This has been kept for security reasons.
+ JS cannot be used for networking applications because no such support is available.
+ JS doesn't have any multi-threading capabilities.

* Content
** Basic
+ [[./consoleMethod.org][console.log]]
+ [[./Comments.org][Comments]]
+ [[./Variable.org][Variable]]
+ [[./LetAndVar.org][Let and Var]]
+ [[./Datatype.org][Data Type]]
+ [[./TypeConversion.org][Type Conversion]]
+ [[./StrictMode.org][Strict Mode]]
+ [[./Operator.org][Operator]]
